version: "3.5"

services:
  postgres:
    container_name: postgres_container
    image: postgres:16.0-alpine
    env_file:
      - ../.env
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    env_file:
      - ../.env
    ports:
      - "5050:80"
    restart: unless-stopped

volumes:
  postgres:
